### ISSUE TITLE
Support mt7621

### ISSUE THREAD

**Issue by AYastrebov** [messense/openwrt-netbird#11]
Can you please add build for ramips/mt7621 platform?

**Comment by messense** [comment]
What does `opkg print-architecture` outputs on this platform?

**Comment by AYastrebov** [comment]
```
root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch mipsel_24kc 10
```

**Comment by AYastrebov** [comment]
I tried to install `netbird_0.8.5-1_mips_24kc.ipk` package, but got an error

![image](https://user-images.githubusercontent.com/739037/183422009-124b6c80-1df8-4dd8-aa00-90162c03b413.png)

**Comment by messense** [comment]
Added in https://github.com/messense/openwrt-netbird/commit/adc02e972e54b34c38b8b7fa8ba0c00b79433043.

Download: https://github.com/messense/openwrt-netbird/releases/download/v0.8.5/netbird_0.8.5-1_mipsel_24kc.ipk

**Comment by AYastrebov** [comment]
Thanks! Now it works
