### ISSUE TITLE
在openwrt的接口设置里如何设置wt0

### ISSUE THREAD

**Issue by ykxVK8yL5L** [messense/openwrt-netbird#13]
感谢大佬的应用 安装、运行很容易完成. 但是防火墙和路由如何设置？ 接口信息里如何设置wt0并加入防火墙？ 通过peer路由所有流量？
期待您的回复 谢谢.

**Comment by gngpp** [comment]
这个跟原生wireguard使用比起来感觉怎么样？

**Comment by messense** [comment]
> 这个跟原生wireguard使用比起来感觉怎么样？

https://netbird.io/docs/wireguard-plus-netbird
