### ISSUE TITLE
Donate the OpenWrt package to upstream netbird or OpenWrt?

### ISSUE THREAD

**Issue by rgl** [messense/openwrt-netbird#29]
Did you ever though about donating this repository code to upstream netbird or OpenWrt?

**Comment by messense** [comment]
If upstream wants to adopt it, sure.

cc @braginini @mlsmaycon

**Comment by BKPepe** [comment]
I see that netbird was added to OpenWrt packages feed in March 2023.
https://github.com/openwrt/packages/pull/20432
