### ISSUE TITLE
Reported version should be match the official release

### ISSUE THREAD

**Issue by rgl** [messense/openwrt-netbird#36]
This is related to the change at https://github.com/messense/openwrt-netbird/issues/28.

`netbird` is now showing the correct version, but it seems its not quite as the official release, as it has an extra `v` letter prefix, and I think it should be removed. Here's a screenshot from https://app.netbird.io/peers:

![image](https://user-images.githubusercontent.com/43356/202284639-3a4219bf-e193-4acc-9ea7-188b741ea4bf.png)

And from the command line:

```console
root@OpenWrt:~# netbird version
v0.10.7
```

Versus what is displayed by the official release:

```console
vagrant@dm1:~$ netbird version
0.10.8
```

**Comment by mlsmaycon** [comment]
opened a PR with the new version, see #37

**Comment by rgl** [comment]
Please note that this issue is not about upgrading to 0.10.8. It's about changing the way the version is reported, that is, v0.10.7 vs 0.10.7

**Comment by mlsmaycon** [comment]
That's true; I totally missed that. Looking here, it seems to be all set correctly; even the workflow outputs the v0.10.7 in the ldflag, see [here](https://github.com/messense/openwrt-netbird/actions/runs/3454900543/jobs/5766540837#step:5:5881)

Can you share the arch type you are running there?

**Comment by rgl** [comment]
It's amd64.

I think we need to remove the v letter at https://github.com/messense/openwrt-netbird/blob/main/netbird/Makefile#L20

**Comment by messense** [comment]
Done in https://github.com/messense/openwrt-netbird/commit/fc3b11e6ea24dbc9996d385e4bf83e5f87077c97
