### ISSUE TITLE
How to use on a mips cpu?

### ISSUE THREAD

**Issue by a1ad** [messense/openwrt-netbird#5]
system type		: Qualcomm Atheros QCA956X ver 1 rev 0
machine			: TP-Link Archer A7 v5
cpu model		: MIPS 74Kc V5.0

Is it even possible? i can't find a release package.

**Comment by messense** [comment]
[netbird_0.8.2-1_mips_24kc.ipk](https://github.com/messense/openwrt-netbird/releases/download/v0.8.2/netbird_0.8.2-1_mips_24kc.ipk)
